version: "3.2"

services:
#Mysql Container
  mysql:
    image: mysql:5.7.34
    container_name: mysql
    hostname: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mysql.env
    restart: always

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /var/www/html/glpi/:/var/www/html/glpi
    restart: always
