version: "3.3"

services:

    mariadb-glpi: 
        image: mariadb
        restart: unless-stopped
        volumes: 
          - ./mariadb-glpi-volume:/var/lib/mysql:rw
        environment: 
          MYSQL_DATABASE: glpidb
          MYSQL_USER: glpi-user 
          MYSQL_PASSWORD: glpi-pass 
          MYSQL_RANDOM_ROOT_PASSWORD: "1" 
        ports: 
          - "3306:3306"


    glpi: 
        image: diouxx/glpi
        restart: unless-stopped
        volumes: 
          - ./glpi/:/var/www/html/glpi
        environment: 
          MYSQL_HOST: mariadb-glpi
          MYSQL_PORT: 3306
          MYSQL_DATABASE: glpidb
          MYSQL_USER: glpi-user
          MYSQL_PASSWORD: glpi-pass
        depends_on: 
          - mariadb-glpi
        ports: 
          - "8200:80"    
