version: "3.2"

services:

  mysql:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=glpi_pass
      - MYSQL_DATABASE=glpi_db
      - MYSQL_USER=glpi_user
      - MYSQL_PASSWORD=glpi_pass
    volumes:
      - ./mysql:/var/lib/mysql     

  glpi:
    image: diouxx/glpi
    container_name : glpi
    restart: unless-stopped
#   hostname: glpi
    ports:
      - "8200:80"
    volumes:
      - ./glpi/glpi/:/var/www/html/glpi            
